#!/usr/bin/env sh
set -eu

manifest_path=${1:-config/repos.csv}

gitlab_base_url=${GITLAB_BASE_URL:-https://gitlab.postmarketos.org}
gitlab_group_path=${GITLAB_GROUP_PATH:-postmarketOS}
gitlab_per_page=${GITLAB_PER_PAGE:-100}
gitlab_api_token=${GITLAB_API_TOKEN:-}

if command -v python3 >/dev/null 2>&1; then
    python_bin=python3
elif command -v python >/dev/null 2>&1; then
    python_bin=python
else
    printf 'python3 or python is required\n' >&2
    exit 1
fi

group_path_encoded=$(
    "$python_bin" - "$gitlab_group_path" <<'PY'
import sys
import urllib.parse

print(urllib.parse.quote(sys.argv[1], safe=""))
PY
)

tmp_dir=$(mktemp -d)

cleanup() {
    rm -rf "$tmp_dir"
}

trap cleanup EXIT INT TERM

records_tmp=$tmp_dir/records.csv
sorted_tmp=$tmp_dir/sorted.csv
headers_tmp=$tmp_dir/headers.txt
body_tmp=$tmp_dir/body.json
output_tmp=$tmp_dir/repos.csv

group_prefix=$gitlab_group_path/
next_page=1

: > "$records_tmp"

while [ -n "$next_page" ]; do
    page=$next_page
    next_page=

    request_url="$gitlab_base_url/api/v4/groups/$group_path_encoded/projects?include_subgroups=true&with_shared=false&simple=true&per_page=$gitlab_per_page&page=$page"

    if [ -n "$gitlab_api_token" ]; then
        curl --fail --silent --show-error \
            --header "PRIVATE-TOKEN: $gitlab_api_token" \
            --dump-header "$headers_tmp" \
            --output "$body_tmp" \
            "$request_url"
    else
        curl --fail --silent --show-error \
            --dump-header "$headers_tmp" \
            --output "$body_tmp" \
            "$request_url"
    fi

    "$python_bin" - "$body_tmp" "$group_prefix" >> "$records_tmp" <<'PY'
import json
import sys

body_path = sys.argv[1]
prefix = sys.argv[2]

with open(body_path, "r", encoding="utf-8") as handle:
    payload = json.load(handle)

if not isinstance(payload, list):
    raise SystemExit("unexpected API payload shape")

for project in payload:
    if project.get("visibility") != "public":
        continue

    source_path = project.get("path_with_namespace") or ""
    if not source_path.startswith(prefix):
        continue

    relative_path = source_path[len(prefix):]
    if not relative_path:
        continue

    target_repo = relative_path.replace("_", "__").replace("/", "_s_")
    print(f"{source_path},{target_repo}")
PY

    next_page=$(
        "$python_bin" - "$headers_tmp" <<'PY'
import sys

headers_path = sys.argv[1]
next_page = ""

with open(headers_path, "r", encoding="utf-8") as handle:
    for line in handle:
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        if key.strip().lower() == "x-next-page":
            next_page = value.strip()
            break

print(next_page)
PY
    )
done

LC_ALL=C sort -u "$records_tmp" > "$sorted_tmp"

entry_count=$(wc -l < "$sorted_tmp" | tr -d '[:space:]')

mkdir -p "$(dirname "$manifest_path")"

{
    printf '# source_path,target_repo\n'
    printf '# generated from %s/%s (visibility=public)\n' "$gitlab_base_url" "$gitlab_group_path"
    printf '# target_repo encoding: slash -> _s_ and underscore -> __\n'
    printf '# regenerated by scripts/sync_public_repos.sh\n'
    cat "$sorted_tmp"
} > "$output_tmp"

if [ -f "$manifest_path" ] && cmp -s "$output_tmp" "$manifest_path"; then
    printf 'manifest unchanged: %s mapping(s) in %s\n' "$entry_count" "$manifest_path"
    exit 0
fi

mv "$output_tmp" "$manifest_path"
printf 'manifest updated: %s mapping(s) written to %s\n' "$entry_count" "$manifest_path"
